version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-ndk-r17b
    steps:
    - checkout
    - run:
        name: Set Properties
        command: |
          mkdir ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run:
        name: Install DeployGate Command Line Tool
        command:
          curl -sSL https://deploygate.com/cli/install | bash
    - run:
        name: Confirm
        command:
          dg --version
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - circle
