version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run:
        name: Test
        command: |
          mkdir ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    filters:
      branches:
        only:
          - circle
