version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-ndk-r17b
    steps:
    - checkout
    - run:
        name: test
        command: |
          touch ./test.apk 
          $APK_NAME=./test.apk
    - run:
        name: test
        command: COMMENT_MESSAGE=`git log -1 --pretty=format:"%s"` 
    - run:
        name: Set Properties
        command: |
          curl -F "token=$DUMMY_TOKEN" -F "file=@APK_NAME" -F "message=$COMMNET_MESSAGE" https://deploygate.com/api/users/$DUMMY_USER_NAME/apps

workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - circle
